### ISSUE TITLE
"Should not be imported" - N50

### ISSUE THREAD

**Issue by NKAmapper** [osmno/progress-visualizer#1]
Linje 475 i main.js: Kunne du sette score til f.eks. 90 for å skille "should not be imported" litt fra de som er fullt importert?
Eventuelt en helt annen farge.

**Comment by mathiash98** [comment]
Godt poeng, la til en svart farge for should not be imported 
![image](https://github.com/osmno/progress-visualizer/assets/5204006/9209dd74-22be-4bf0-ba40-7c70f0fc5327)
