### ISSUE TITLE
Kommunereform 2024

### ISSUE THREAD

**Issue by NKAmapper** [osmno/progress-visualizer#2]
Kunne du legge om til nye kommunenummer som kom 1.1.2024 ?
Ikke implementert på alle wiki-sidene ennå, men kommer.

**Comment by mathiash98** [comment]
Da er nye kommuner lagt til og ting ser bra ut 👍🏼

**Comment by NKAmapper** [comment]
Ser at det ble litt trøbbel med grensene.
Her er kommunepolygonene som ble brukt sist (ferdig forenklet):
https://api.kartverket.no/kommuneinfo/v1/kommuner/illustrasjonskart

**Comment by mathiash98** [comment]
Oppdatert til å bruke kartverkets api, ble mye finere det der.

Brukte en geojson simplify function for å redusere filstørrelse fra 13MB til 1MB, men kartverket sitt er bare 220KB så det er supert
